bump_version: null
lint:
  files_unchanged:
    - assets/nf-core-nanorepertoire_logo_light.png
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Davide Bagordo
  description: pipeline to characterise the repertoire of nanobodies
  force: false
  is_nfcore: true
  name: nanorepertoire
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
